import { useEffect, useMemo, useState } from "react";
import { api, type Proposal, type Task } from "../api";
import "./business.css";

type View="overview"|"proposals"|"progress";
export default function BusinessApp(){
 const [view,setView]=useState<View>("overview"),[tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<number|null>(null),[proposals,setProposals]=useState<Proposal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[version,setVersion]=useState(0);
 useEffect(()=>{let ok=true;setLoading(true);setError("");api.catalog().then(d=>{if(ok){setTasks(d);setSelected(x=>x&&d.some(t=>t.id===x)?x:d[0]?.id??null)}}).catch(e=>ok&&setError((e as Error).message)).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[version]);
 useEffect(()=>{if(!selected){setProposals([]);return}let ok=true;api.taskProposals(selected).then(d=>ok&&setProposals(d)).catch(e=>ok&&setError((e as Error).message));return()=>{ok=false}},[selected,version]);
 const task=tasks.find(t=>t.id===selected)||null,accepted=proposals.filter(p=>p.status==="accepted");
 const stats=useMemo(()=>({active:tasks.filter(t=>t.status!=="closed").length,proposals:tasks.reduce((s,t)=>s+t.proposals_count,0),running:tasks.filter(t=>t.status==="in_progress").length,done:tasks.filter(t=>t.status==="closed").length}),[tasks]);
 const decide=async(id:number,d:"accept"|"reject")=>{try{await api.decide(id,d);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}};
 const milestone=async(id:number)=>{const note=prompt("Название завершённого этапа","Этап завершён");if(note===null)return;try{await api.milestone(id,note);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}};
 return <div className="bz"><header className="bz-nav"><a href="#/">✦ AI <b>SANA</b></a><nav><button onClick={()=>setView("overview")}>Мои задачи</button><button onClick={()=>setView("proposals")}>Команды</button><button onClick={()=>setView("progress")}>Прогресс</button></nav><a className="bz-new" href="#/">+ Новая задача</a></header>
 <main><section className="bz-hero"><div><small>BUSINESS CONTROL CENTER</small><h1>От задачи к <em>результату.</em></h1><p>Готовность, отклики, выбор команды и подтверждённые этапы — в одном рабочем пространстве.</p></div><span>● LIVE WORKSPACE</span></section>
 <section className="bz-stats">{[["Активные задачи",stats.active],["Отклики",stats.proposals],["Команды выбраны",stats.running],["Завершено",stats.done]].map(([l,n])=><div key={l}><small>{l}</small><strong>{n}</strong></div>)}</section>
 {loading&&<div className="bz-state">Загружаем dashboard…</div>}{error&&<div className="bz-error">{error}<button onClick={()=>setVersion(v=>v+1)}>Повторить</button></div>}
 {!loading&&!error&&tasks.length===0&&<div className="bz-empty"><b>Пока нет задач</b><span>Создайте первую задачу через Challenge Builder.</span><a href="#/">Создать задачу →</a></div>}
 {tasks.length>0&&<div className="bz-space"><aside><div className="bz-side-title">МОИ ЗАДАЧИ <b>{tasks.length}</b></div>{tasks.map(t=><button key={t.id} className={t.id===selected?"on":""} onClick={()=>setSelected(t.id)}><span>{t.status==="open"?"OPEN":t.status==="in_progress"?"IN PROGRESS":"CLOSED"} · {t.topic}</span><h3>{t.title}</h3><footer><small>{t.proposals_count} откликов</small><b>{t.score}/100</b></footer></button>)}</aside>
 {task&&<section className="bz-detail"><header><div><small>{task.topic} · TASK #{task.id}</small><h2>{task.title}</h2><p>{task.card.need||task.card.context||"Описание не заполнено"}</p></div><div className="bz-score"><b>{task.score}</b><span>/100</span><small>{task.level_label}</small></div></header><div className="bz-bar"><i style={{width:task.score+"%"}}/></div>
 <nav className="bz-tabs"><button className={view==="overview"?"on":""} onClick={()=>setView("overview")}>Обзор</button><button className={view==="proposals"?"on":""} onClick={()=>setView("proposals")}>Отклики · {proposals.length}</button><button className={view==="progress"?"on":""} onClick={()=>setView("progress")}>Milestones</button></nav>
 {view==="overview"&&<div className="bz-info">{[["Что нужно решить",task.card.need],["Ожидаемый результат",task.card.expected_result],["Критерии успеха",task.card.success_criteria],["Доступные данные",task.card.data]].map(([a,b])=><article key={a}><small>{a}</small><p>{b||"Не указано"}</p></article>)}</div>}
 {view==="proposals"&&<div><div className="bz-title"><div><small>TEAM CANDIDATES</small><h3>Сравните команды</h3></div><p>GPT Match помогает сравнить профиль, но решение принимает бизнес.</p></div><div className="bz-grid">{proposals.map(p=>{const skills=[...new Set([...p.team.skills,...p.team.tech])],match=Math.min(98,72+skills.filter(x=>task.tags.some(y=>y.toLowerCase().includes(x.toLowerCase()))).length*7+Math.round(task.score/10));return <article className={"bz-prop "+p.status} key={p.id}><div className="bz-prop-top"><div><small>{p.status==="pending"?"CANDIDATE":p.status}</small><h4>{p.team.name}</h4></div><div><b>{match}%</b><small>GPT MATCH</small></div></div><p>{p.idea}</p><div className="bz-skills">{skills.slice(0,5).map(s=><span key={s}>{s}</span>)}</div><footer><span>⏱ {p.deadline}</span><span>★ {p.team.points}</span></footer>{p.status==="pending"?<div className="bz-actions"><button onClick={()=>decide(p.id,"accept")}>Выбрать</button><button onClick={()=>decide(p.id,"reject")}>Отклонить</button></div>:<strong className="bz-decision">{p.status==="accepted"?"✓ Команда выбрана":"Отклонено"}</strong>}</article>})}</div>{proposals.length===0&&<div className="bz-empty">Откликов пока нет</div>}</div>}
 {view==="progress"&&<div className="bz-progress"><div className="bz-journey">{[["✓","Задача создана"],["✓","Опубликована"],[accepted.length?"✓":"3","Команда выбрана"],["4","Milestone"],["5","Результат"]].map(([n,l],i)=><div className={i<2||i===2&&accepted.length?"done":""} key={l}><i>{n}</i><b>{l}</b></div>)}</div>{accepted.map(p=><article className="bz-mile" key={p.id}><div><small>SELECTED TEAM</small><h3>{p.team.name}</h3><p>{p.plan}</p></div><button onClick={()=>milestone(p.id)}>+ Подтвердить milestone</button>{p.milestones.map((m,i)=><span key={i}>✓ {m.note} <b>+{m.points}</b></span>)}</article>)}</div>}
 </section>}</div>}</main></div>
}