import { useEffect, useMemo, useState } from "react";
import { api, type Proposal, type Task } from "../api";
import "./business.css";
import { LanguageSwitch, tr, useLanguage } from "../i18n";

type View="overview"|"proposals"|"progress";
export default function BusinessApp(){
 const [lang]=useLanguage();
 const t=(ru:string,en:string)=>tr(lang,ru,en);
 const [view,setView]=useState<View>("overview"),[tasks,setTasks]=useState<Task[]>([]),[selected,setSelected]=useState<number|null>(null),[proposals,setProposals]=useState<Proposal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[version,setVersion]=useState(0);
 useEffect(()=>{let ok=true;setLoading(true);setError("");api.catalog().then(d=>{if(ok){setTasks(d);setSelected(x=>x&&d.some(t=>t.id===x)?x:d[0]?.id??null)}}).catch(e=>ok&&setError((e as Error).message)).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[version]);
 useEffect(()=>{if(!selected){setProposals([]);return}let ok=true;api.taskProposals(selected).then(d=>ok&&setProposals(d)).catch(e=>ok&&setError((e as Error).message));return()=>{ok=false}},[selected,version]);
 const task=tasks.find(t=>t.id===selected)||null,accepted=proposals.filter(p=>p.status==="accepted");
 const stats=useMemo(()=>({active:tasks.filter(t=>t.status!=="closed").length,proposals:tasks.reduce((s,t)=>s+t.proposals_count,0),running:tasks.filter(t=>t.status==="in_progress").length,done:tasks.filter(t=>t.status==="closed").length}),[tasks]);
 const decide=async(id:number,d:"accept"|"reject")=>{try{await api.decide(id,d);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}};
 const milestone=async(id:number)=>{const note=prompt(t("Название завершённого этапа","Completed milestone name"),t("Этап завершён","Milestone completed"));if(note===null)return;try{await api.milestone(id,note);setVersion(v=>v+1)}catch(e){setError((e as Error).message)}};
 return <div className="bz"><header className="bz-nav"><a href="#/">✦ AI <b>SANA</b></a><nav><button onClick={()=>setView("overview")}>{t("Мои задачи","My challenges")}</button><button onClick={()=>setView("proposals")}>{t("Команды","Teams")}</button><button onClick={()=>setView("progress")}>{t("Прогресс","Progress")}</button></nav><LanguageSwitch/><a className="bz-new" href="#/">{t("+ Новая задача","+ New challenge")}</a></header>
 <main><section className="bz-hero"><div><small>BUSINESS CONTROL CENTER</small><h1>{t("От задачи к ","From challenge to ")}<em>{t("результату.","impact.")}</em></h1><p>{t("Готовность, отклики, выбор команды и подтверждённые этапы — в одном рабочем пространстве.","Readiness, proposals, team selection and confirmed milestones — in one workspace.")}</p></div><span>● LIVE WORKSPACE</span></section>
 <section className="bz-stats">{[[t("Активные задачи","Active challenges"),stats.active],[t("Отклики","Proposals"),stats.proposals],[t("Команды выбраны","Teams selected"),stats.running],[t("Завершено","Completed"),stats.done]].map(([l,n])=><div key={l}><small>{l}</small><strong>{n}</strong></div>)}</section>
 {loading&&<div className="bz-state">{t("Загружаем dashboard…","Loading dashboard…")}</div>}{error&&<div className="bz-error">{error}<button onClick={()=>setVersion(v=>v+1)}>{t("Повторить","Retry")}</button></div>}
 {!loading&&!error&&tasks.length===0&&<div className="bz-empty"><b>{t("Пока нет задач","No challenges yet")}</b><span>{t("Создайте первую задачу через Challenge Builder.","Create your first challenge with Challenge Builder.")}</span><a href="#/">{t("Создать задачу →","Create challenge →")}</a></div>}
 {tasks.length>0&&<div className="bz-space"><aside><div className="bz-side-title">{t("МОИ ЗАДАЧИ","MY CHALLENGES")} <b>{tasks.length}</b></div>{tasks.map(t=><button key={t.id} className={t.id===selected?"on":""} onClick={()=>setSelected(t.id)}><span>{t.status==="open"?"OPEN":t.status==="in_progress"?"IN PROGRESS":"CLOSED"} · {t.topic}</span><h3>{t.title}</h3><footer><small>{t.proposals_count} {lang==="ru"?"откликов":"proposals"}</small><b>{t.score}/100</b></footer><span className="bz-view-proposals" onClick={(e)=>{e.stopPropagation();setSelected(t.id);setView("proposals")}}>👥 {t("Посмотреть отклики","View proposals")} ({t.proposals_count}) →</span></button>)}</aside>
 {task&&<section className="bz-detail"><header><div><small>{task.topic} · TASK #{task.id}</small><h2>{task.title}</h2><p>{task.card.need||task.card.context||t("Описание не заполнено","Description is missing")}</p></div><div className="bz-score"><b>{task.score}</b><span>/100</span><small>{task.level_label}</small></div></header><div className="bz-bar"><i style={{width:task.score+"%"}}/></div>
 <nav className="bz-tabs"><button className={view==="overview"?"on":""} onClick={()=>setView("overview")}>{t("Обзор","Overview")}</button><button className={view==="proposals"?"on":""} onClick={()=>setView("proposals")}>{t("Отклики","Proposals")} · {proposals.length}</button><button className={view==="progress"?"on":""} onClick={()=>setView("progress")}>Milestones</button></nav>
 {view==="overview"&&<div className="bz-info">{[[t("Что нужно решить","Problem to solve"),task.card.need],[t("Ожидаемый результат","Expected result"),task.card.expected_result],[t("Критерии успеха","Success criteria"),task.card.success_criteria],[t("Доступные данные","Available data"),task.card.data]].map(([a,b])=><article key={a}><small>{a}</small><p>{b||t("Не указано","Not specified")}</p></article>)}</div>}
 {view==="proposals"&&<div><div className="bz-title"><div><small>TEAM CANDIDATES</small><h3>{t("Сравните команды","Compare teams")}</h3></div><p>{t("GPT Match помогает сравнить профиль, но решение принимает бизнес.","GPT Match helps compare profiles, while the business makes the final decision.")}</p></div><div className="bz-grid">{proposals.map(p=>{const skills=[...new Set([...p.team.skills,...p.team.tech])],match=Math.min(98,72+skills.filter(x=>task.tags.some(y=>y.toLowerCase().includes(x.toLowerCase()))).length*7+Math.round(task.score/10));return <article className={"bz-prop "+p.status} key={p.id}><div className="bz-prop-top"><div><small>{p.status==="pending"?"CANDIDATE":p.status}</small><h4>{p.team.name}</h4></div><div><b>{match}%</b><small>GPT MATCH</small></div></div><p>{p.idea}</p><div className="bz-skills">{skills.slice(0,5).map(s=><span key={s}>{s}</span>)}</div><footer><span>⏱ {p.deadline}</span><span>★ {p.team.points}</span></footer>{p.status==="pending"?<div className="bz-actions"><button onClick={()=>decide(p.id,"accept")}>{t("Выбрать","Select")}</button><button onClick={()=>decide(p.id,"reject")}>{t("Отклонить","Reject")}</button></div>:<strong className="bz-decision">{p.status==="accepted"?t("✓ Команда выбрана","✓ Team selected"):t("Отклонено","Rejected")}</strong>}</article>})}</div>{proposals.length===0&&<div className="bz-empty">{t("Откликов пока нет","No proposals yet")}</div>}</div>}
 {view==="progress"&&<div className="bz-progress"><div className="bz-journey">{[["✓",t("Задача создана","Challenge created")],["✓",t("Опубликована","Published")],[accepted.length?"✓":"3",t("Команда выбрана","Team selected")],["4","Milestone"],["5",t("Результат","Result")]].map(([n,l],i)=><div className={i<2||i===2&&accepted.length?"done":""} key={l}><i>{n}</i><b>{l}</b></div>)}</div>{accepted.map(p=><article className="bz-mile" key={p.id}><div><small>SELECTED TEAM</small><h3>{p.team.name}</h3><p>{p.plan}</p></div><button onClick={()=>milestone(p.id)}>{t("+ Подтвердить milestone","+ Confirm milestone")}</button>{p.milestones.map((m,i)=><span key={i}>✓ {m.note} <b>+{m.points}</b></span>)}</article>)}</div>}
 </section>}</div>}</main></div>
}